default:
  outputs:
    dev:
      type: postgres
      host: localhost
      user: airflow
      password: airflow
      port: 5432
      dbname: weather_db
      schema: public
      threads: 4
  target: dev
